require('dotenv').config()
const Sequelize = require('sequelize')

const {CONNECTION_STRING} = process.env

const sequelize = new Sequelize(CONNECTION_STRING, {
    dialect: 'postgres',
    dialectOptions: {
        ssl: {
            rejectUnauthorized: false
        }
    }
})

module.exports = {
    seed: (req, res) => {
        sequelize.query(`
        drop table if exists bab_users;
        drop table if exists bab_champions;
        drop table if exists bab_items;
        
        create table bab_users (
            user_id serial primary key,
            first_name varchar(100),
            last_name varchar(100),
            username varchar(100),
            password varchar(100)
        );

        create table bab_champions (
            champion_id serial primary key,
            champ_name varchar(200)
        );

        create table bab_items (
            item_id serial primary key,
            item_name varchar(250)
        );

        insert into bab_users (first_name, last_name, username, password)
        values ('Joseph', 'Al-Abudi', 'Jololio', '12345');

        insert into bab_champions (champ_name)
        values ('Aatrox'),
            ('Ahri'),
            ('Akali'),
            ('Akshan'),
            ('Alistar'),
            ('Amumu'),
            ('Anivia'),
            ('Annie'),
            ('Aphelios'),
            ('Ashe'),
            ('Aurelion Sol'),
            ('Azir'),
            ('Bard'),
            ('Blitzcrank'),
            ('Brand'),
            ('Braum'),
            ('Bel Veth'),
            ('Caitlyn'),
            ('Camille'),
            ('Cassiopeia'),
            ('Cho Gath'),
            ('Corki'),
            ('Darius'),
            ('Diana'),
            ('Dr. Mundo'),
            ('Draven'),
            ('Ekko'),
            ('Elise'),
            ('Evelynn'),
            ('Ezreal'),
            ('Fiddlesticks'),
            ('Fiora'),
            ('Fizz'),
            ('Galio'),
            ('Gangplank'),
            ('Garen'),
            ('Gnar'),
            ('Gragas'),
            ('Graves'),
            ('Gwen'),
            ('Hecarim'),
            ('Heimerdinger'),
            ('Illaoi'),
            ('Irelia'),
            ('Ivern'),
            ('Janna'),
            ('Jarvan IV'),
            ('Jax'),
            ('Jayce'),
            ('Jhin'),
            ('Jinx'),
            ('Kaisa'),
            ('Kalista'),
            ('Karma'),
            ('Karthus'),
            ('Kassadin'),
            ('Katarina'),
            ('Kayle'),
            ('Kayn'),
            ('Kennen'),
            ('Kha Zix'),
            ('Kindred'),
            ('Kled'),
            ('Kog Maw'),
            ('LeBlanc'),
            ('Lee Sin'),
            ('Leona'),
            ('Lillia'),
            ('Lissandra'),
            ('Lucian'),
            ('Lulu'),
            ('Lux'),
            ('Malphite'),
            ('Malzahar'),
            ('Maokai'),
            ('Master Yi'),
            ('Miss Fortune'),
            ('Mordekaiser'),
            ('Morgana'),
            ('Nami'),
            ('Nasus'),
            ('Nautilus'),
            ('Neeko'),
            ('Nidalee'),
            ('Nocturne'),
            ('Nunu & Willump'),
            ('Olaf'),
            ('Orianna'),
            ('Ornn'),
            ('Pantheon'),
            ('Poppy'),
            ('Pyke'),
            ('Qiyana'),
            ('Quinn'),
            ('Rakan'),
            ('Rammus'),
            ('Rek Sai'),
            ('Rell'),
            ('Renata Glasc'),
            ('Renekton'),
            ('Rengar'),
            ('Riven'),
            ('Rumble'),
            ('Ryze'),
            ('Samira'),
            ('Sejuani'),
            ('Senna'),
            ('Seraphine'),
            ('Sett'),
            ('Shaco'),
            ('Shen'),
            ('Shyvana'),
            ('Singed'),
            ('Sion'),
            ('Sivir'),
            ('Skarner'),
            ('Sona'),
            ('Soraka'),
            ('Swain'),
            ('Sylas'),
            ('Syndra'),
            ('Tahm Kench'),
            ('Taliyah'),
            ('Talon'),
            ('Taric'),
            ('Teemo'),
            ('Thresh'),
            ('Tristana'),
            ('Trundle'),
            ('Tryndamere'),
            ('Twisted Fate'),
            ('Twitch'),
            ('Udyr'),
            ('Urgot'),
            ('Varus'),
            ('Vayne'),
            ('Veigar'),
            ('Vel Koz'),
            ('Vex'),
            ('Vi'),
            ('Viego'),
            ('Viktor'),
            ('Vladimir'),
            ('Volibear'),
            ('Warwick'),
            ('Wukong'),
            ('Xayah'),
            ('Xerath'),
            ('Xin Zhao'),
            ('Yasuo'),
            ('Yone'),
            ('Yorick'),
            ('Yuumi'),
            ('Zac'),
            ('Zed'),
            ('Zeri'),
            ('Ziggs'),
            ('Zilean'),
            ('Zoe'),
            ('Zyra');
        
        insert into bab_items (item_name)
        values('Crown of the Shattered Queen'),
            ('Divine Sunderer'),
            ('Duskblade of Draktharr'),
            ('Eclipse'),
            ('Evenshroud'),
            ('Everfrost'),
            ('Frostfire Gauntlet'),
            ('Galeforce'),
            ('Goredrinker'),
            ('Hextech Rocketbelt'),
            ('Immortal Shieldbow'),
            ('Imperial Mandate'),
            ('Kraken Slayer'),
            ('Liandrys Anguish'),
            ('Locket of the Iron Solari'),
            ('Ludens Tempest'),
            ('Moonstone Renewer'),
            ('Night Harvester'),
            ('Prowlers Claw'),
            ('Riftmaker'),
            ('Shurelyas Battlesong'),
            ('Stridebreaker'),
            ('Sunfire Aegis'),
            ('Trinity Force'),
            ('Turbo Chemtank'),
            ('Abyssal Mask'),
            ('Anthemas Chains'),
            ('Archangels Staff'),
            ('Ardent Censer'),
            ('Axiom Arc'),
            ('Banshees Veil'),
            ('Black Cleaver'),
            ('Black Mist Scythe'),
            ('Blade of the Ruined King'),
            ('Bloodthirster'),
            ('Bulwark of the Mountain'),
            ('Chempunk Chainsword'),
            ('Chemtech Putrifier'),
            ('Cosmic Drive'),
            ('Dead Mans Plate'),
            ('Deaths Dance'),
            ('Demonic Embrace'),
            ('Edge of Night'),
            ('Essence Reaver'),
            ('Fimbulwinter'),
            ('Force of Nature'),
            ('Frozen Heart'),
            ('Gargoyle Stoneplate'),
            ('Guardian Angel'),
            ('Guinsoos Rageblade'),
            ('Horizon Focus'),
            ('Hullbreaker'),
            ('Infinity Edge'),
            ('Knights Vow'),
            ('Lich Bane'),
            ('Lord Dominiks Regards'),
            ('Manamune'),
            ('Maw of Malmortius'),
            ('Mejais Soulstealer'),
            ('Mercurial Scimitar'),
            ('Mikaels Blessing'),
            ('Morellonomicon'),
            ('Mortal Reminder'),
            ('Nashors Tooth'),
            ('Navori Quickblades'),
            ('Pauldrons of Whiterock'),
            ('Phantom Dancer'),
            ('Rabadons Deathcap'),
            ('Randuins Omen'),
            ('Rapid Firecannon'),
            ('Ravenous Hydra'),
            ('Redemption'),
            ('Runaans Hurricane'),
            ('Rylais Crystal Scepter'),
            ('Serpents Fang'),
            ('Seryldas Grudge'),
            ('Shadowflame'),
            ('Shard of True Ice'),
            ('Silvermere Dawn'),
            ('Spirit Visage'),
            ('Staff of Flowing Water'),
            ('Steraks Gage'),
            ('Stormrazor'),
            ('The Collector'),
            ('Thornmail'),
            ('Titanic Hydra'),
            ('Umbral Glaive'),
            ('Vigilant Wardstone'),
            ('Void Staff'),
            ('Warmogs Armor'),
            ('Winters Approach'),
            ('Wits End'),
            ('Youmuus Ghostblade'),
            ('Zekes Convergence'),
            ('Zhonyas Hourglass');
        `).then(() => {
            console.log('DB seeded!')
            res.sendStatus(200)
        }).catch(err => console.log('error sending DB', err))
    }
}